### ISSUE TITLE
nginx dup error

### ISSUE THREAD

**Issue by cyris69** [liaralabs/swizzin#118]
So I saw that the install/update script for ombi v3 was good to go so just left the default installation I had been running and just installed over it and that's when I got the error. I remove any locations with /ombi/ besides the one from the wiki. I wasn't sure how to get my current ombi installation to show in the web GUI tab so seemed like a good idea /s

Still can't figure it out.

```
**cyris69@QB:/etc/nginx/sites-enabled$ sudo service nginx restart**
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**cyris69@QB:/etc/nginx/sites-enabled$ systemctl status nginx.service**
 nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-07-27 18:06:41 EDT; 38s ago
  Process: 6855 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jul 27 18:06:41 QB systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 27 18:06:41 QB nginx[6855]: nginx: [warn] "ssl_stapling" ignored, issuer certificate not found
Jul 27 18:06:41 QB nginx[6855]: nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_s
Jul 27 18:06:41 QB nginx[6855]: nginx: [emerg] duplicate location "/ombi/" in /etc/nginx/sites-enabled/default:45
Jul 27 18:06:41 QB nginx[6855]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 27 18:06:41 QB systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 27 18:06:41 QB systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Jul 27 18:06:41 QB systemd[1]: nginx.service: Unit entered failed state.
Jul 27 18:06:41 QB systemd[1]: nginx.service: Failed with result 'exit-code'.
**cyris69@QB:/etc/nginx/sites-enabled$ journalctl -xe**
Jul 27 18:08:51 QB Ombi[7225]: Copyright (C) 2018 Ombi
Jul 27 18:08:51 QB Ombi[7225]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Jul 27 18:08:51 QB Ombi[7225]:                of URL prefixes to which the server should respond. For example,
Jul 27 18:08:51 QB Ombi[7225]:                http://localhost:123. Use "*" to indicate that the server should
Jul 27 18:08:51 QB Ombi[7225]:                listen for requests on any IP address or hostname using the
Jul 27 18:08:51 QB Ombi[7225]:                specified port and protocol (for example, http://*:5000). The
Jul 27 18:08:51 QB Ombi[7225]:                protocol (http:// or https://) must be included with each URL.
Jul 27 18:08:51 QB Ombi[7225]:                Supported formats vary between servers.
Jul 27 18:08:51 QB Ombi[7225]:   --storage    Storage path, where we save the logs and database
Jul 27 18:08:51 QB Ombi[7225]:   --baseurl    The base URL for reverse proxy scenarios
Jul 27 18:08:51 QB Ombi[7225]:   --help       Display this help screen.
Jul 27 18:08:51 QB Ombi[7225]:   --version    Display version information.
Jul 27 18:08:53 QB Ombi[7225]: Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.Data.Sqlite.SqliteConnection.Open()
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
Jul 27 18:08:53 QB Ombi[7225]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
Jul 27 18:08:53 QB Ombi[7225]:    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 48
Jul 27 18:08:53 QB systemd[1]: ombi.service: Main process exited, code=dumped, status=6/ABRT
Jul 27 18:08:53 QB systemd[1]: ombi.service: Unit entered failed state.
Jul 27 18:08:53 QB systemd[1]: ombi.service: Failed with result 'core-dump'.
**cyris69@QB:/etc/nginx/sites-enabled$ sudo nginx -t -c /etc/nginx/nginx.conf**                                                                  
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
nginx: [emerg] duplicate location "/ombi/" in /etc/nginx/sites-enabled/default:45
nginx: configuration file /etc/nginx/nginx.conf test failed
cyris69@QB:/etc/nginx/sites-enabled$
```

Default site file:
https://gist.github.com/cyris69/64d2e00fb5435f760afe836dd04d6add

nginx.conf:
https://gist.github.com/cyris69/eaa8537e2a47d39dd51c02720c77597c

**Comment by liaralabs** [comment]
Relevant error:

```
nginx: [emerg] duplicate location "/ombi/" in /etc/nginx/sites-enabled/default:45
```

Not sure why Ombi isn't starting though. Could be permission issues on the /opt/Ombi folder. Recently we moved the storage to /etc/Ombi (make sure Ombi.db is there and that whole folder and its contents are owned by ombi:nogroup), whereas the /opt/Ombi folder should be owned by root:root.

**Comment by cyris69** [comment]
I found the duplicate, since I had ombi already installed there was no ombi.conf in nginx apps. Installing over it created that. So removed the lines from my default site and just put them into the ombi.conf. 

Group:Owner
/opt/Ombi is root:root 0755
/etc/Ombi is nogroup [65534]:ombi [115] 0755
/etc/Ombi contents are same but 0644
Do I need to flip the nogroup:ombi?

**Comment by cyris69** [comment]
Sorry, the Owner is ombi, i listed them as Group:Owner as I was just going by how winSCP has group drop box then under is owner drop down.

**Comment by liaralabs** [comment]
Is your /etc/systemd/system/ombi.service also using the line --storage /etc/Ombi?

**Comment by cyris69** [comment]
Doesn't appear so, however I thought the default ports used to be 5000, but after installing these have been showing port 3000 and I've been trying to change them.

```
[Unit]
Description=Ombi - PMS Requests System
After=network-online.target

[Service]
User=ombi
Group=nogroup
WorkingDirectory=/opt/Ombi/
ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

```

**Comment by liaralabs** [comment]
Port has been 3000 for some time. Whatever you use, just make sure it's the same in nginx.

Add `--storage /etc/Ombi` to ExecStart and `sudo systemctl daemon-reload`. This should tell Ombi to use that directory for storage and should start working.

**Comment by cyris69** [comment]
Ok, changed to `ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:5000 --storage /etc/Ombi`

It took a minute but I can access it now from swizzin :) Still shows as offline in the WebUI but beggars can't be choosers. Thanks. Going to make sure it can still perform as it did.

**Comment by liaralabs** [comment]
Hey, that's probably actually a bug 🙂 

In `/srv/panel/inc/config.php` on line 250 you should see:

`$ombi = processExists("ombi",$username);`

Change that to
`$ombi = processExists("ombi",ombi);`

And then `systemctl restart php7.0-fpm` to reload the cache

**Comment by cyris69** [comment]
there wasn't a `$ombi = processExists("ombi",$username);` so just added your proper example.

However further down there is 
```
  $ombi = isEnabled("ombi", $username);
    $cbodypr .= $ombi;
```

Do I need to mess with that because still red light in webui

**Comment by cyris69** [comment]
I will say, I haven't seen such low resource usages now though :)
I'm content with how it is now, but if indeed a bug I'm your lab rat.

**Comment by cyris69** [comment]
Changed back and updated and we have a green light :) Now, the 1 is gone but no slider so I'm sure I entered an extra space or something somewhere.

**Comment by liaralabs** [comment]
I've just updated the panel to the proper code and everything should be good now.
