### ISSUE TITLE
Ombi 502 Bad Gateway

### ISSUE THREAD

**Issue by EdTheLoon** [liaralabs/swizzin#263]
* Installed ombi using `sudo box install ombi` which ran with no errors reported. 
* Swizzin dash shows the service as red and not running. 
* Clicking through to Ombi on the swizzin dash shows error 502 bad gateway. 
* A restart of the service does not appear to work.

`sudo journalctl -xe` gave the following output: 

```
Feb 09 22:16:15 somehost Ombi[812]: Hello, welcome to Ombi
Feb 09 22:16:15 somehost Ombi[812]: Valid options are:
Feb 09 22:16:15 somehost Ombi[812]: Ombi 3.0.4892-master
Feb 09 22:16:15 somehost Ombi[812]: Copyright (C) 2020 Ombi
Feb 09 22:16:15 somehost Ombi[812]:   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
Feb 09 22:16:15 somehost Ombi[812]:                of URL prefixes to which the server should respond. For example,
Feb 09 22:16:15 somehost Ombi[812]:                http://localhost:123. Use "*" to indicate that the server should
Feb 09 22:16:15 somehost Ombi[812]:                listen for requests on any IP address or hostname using the
Feb 09 22:16:15 somehost Ombi[812]:                specified port and protocol (for example, http://*:5000). The
Feb 09 22:16:15 somehost Ombi[812]:                protocol (http:// or https://) must be included with each URL.
Feb 09 22:16:15 somehost Ombi[812]:                Supported formats vary between servers.
Feb 09 22:16:15 somehost Ombi[812]:   --storage    Storage path, where we save the logs and database
Feb 09 22:16:15 somehost Ombi[812]:   --baseurl    The base URL for reverse proxy scenarios
Feb 09 22:16:15 somehost Ombi[812]:   --demo       Demo mode, you will never need to use this, fuck that fruit
Feb 09 22:16:15 somehost Ombi[812]:                company...
Feb 09 22:16:15 somehost Ombi[812]:   --help       Display this help screen.
Feb 09 22:16:15 somehost Ombi[812]:   --version    Display version information.
Feb 09 22:16:16 somehost Ombi[812]: Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'no such table: ApplicationConfiguration'.
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod exe
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDict
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext
Feb 09 22:16:16 somehost Ombi[812]:    at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNe
Feb 09 22:16:16 somehost Ombi[812]:    at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
Feb 09 22:16:16 somehost Ombi[812]:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Feb 09 22:16:16 somehost Ombi[812]:    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 61
Feb 09 22:16:16 somehost systemd[1]: ombi.service: Main process exited, code=dumped, status=6/ABRT
Feb 09 22:16:16 somehost systemd[1]: ombi.service: Failed with result 'core-dump'.
```

Attempted a 'fix' by doing `sudo chown -vR ombi:ombi /opt/Ombi` and restarted the service. Nothing changed.

Culprit seems to be this part:
```
Feb 09 22:16:16 somehost Ombi[812]: Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'no such table: ApplicationConfiguration'.
``` 

Some of the permissions:
```
user@somehost etc: ls -Alh /etc/ | grep Ombi
drwxr-xr-x  2 ombi nogroup   4.0K Jan 20 05:41 Ombi
user@somehost etc: ls -Alh /opt/ | grep Ombi
drwxr-xr-x  6 ombi     ombi     40K Feb  9 21:57 Ombi
user@somehost etc: ls -AlhR /etc/Ombi/ | grep Ombi
/etc/Ombi/:
-rw-r--r-- 1 ombi nogroup 12K Jan 17 06:55 OmbiSettings.db
```

**Comment by liaralabs** [comment]
Unfortunately I cannot replicate your issue in a fresh test environment using Debian 10.

Can you please give a bit more info about your OS and environment?

Correct permissions for `/etc/Ombi` should be `ombi:nogroup`

```
drwxr-xr-x  2 ombi nogroup   4096 Feb 10 20:15 Logs
-rw-r--r--  1 ombi nogroup 331776 Feb 10 20:16 Ombi.db
-rw-r--r--  1 ombi nogroup  98304 Feb 10 20:17 OmbiExternal.db
-rw-r--r--  1 ombi nogroup  24576 Feb 10 20:17 OmbiSettings.db
```

Do you not have an Ombi.db file?

**Comment by EdTheLoon** [comment]
```
user@somehost /etc: sudo chgrp -vR nogroup Ombi/
group of 'Ombi/OmbiSettings.db' retained as nogroup
group of 'Ombi/' retained as nogroup
user@somehost /etc: ls -Alh Ombi/
total 12K
-rw-r--r-- 1 ombi nogroup 12K Jan 17 06:55 OmbiSettings.db
user@somehost /etc: 
```
As you can see only one file present in the `/etc/Ombi/` directory after installation. I don't have the terminal output from the installation but there was definitely zero errors reported throughout the process. Also OmbiSettings.db does not have any tables except one named `__EFMigrationsHistory`

Running 64-bit Ubuntu 18.04 on the system, packages up-to-date.
Kernel x86_64 Linux 4.15.0-76-generic
`box` is up-to-date.
The system is a swizzin box system only, with only the packages installed by box being used. 
From fresh install of Ubuntu this is what I did:
* Fresh install of Ubuntu 18.04 because I hadn't set up RAID0 correctly, Ombi had failed to work on previous install as well.
* Check partitions and RAID0 set up correctly
* Update the system and reboot
* User administration, ssh set up and disabling root login, password login etc
* Install swizzin
* Configure rtorrent, rutorrent, jackett, radarr, sonarr, plex and tautulli
* A few weeks later decide to install ombi using `sudo box install ombi`

Not sure what other information you're looking for. I can probably fix this if I had the default files in `/etc/Ombi`. Also worth noting I don't have a `Logs` directory within `/etc/Ombi` either. Going to check your github files to see if there are default files present.

**Comment by Saetun** [comment]
issue is that the current install package on Ubuntu 18.04 doesn't use /etc/Ombi

edit : /etc/systemd/system/ombi.service and remove the reference to /etc/Ombi on the execstart line and it works fine.

Used the Ubuntu section at https://github.com/tidusjar/Ombi/wiki/Installation to figure this out.

**Comment by liaralabs** [comment]
I cannot replicate the issue under Ubuntu 18.04 either.

If Ubuntu isn't using `/etc/Ombi` for storage, it should be. Several iterations ago, the storage was separated from the application itself to make managing user data easier. The default systemd service also utilizes the `storage` argument as well. Moving your storage away from `/etc/Ombi` may have unintended side-effects in the future.

swizzin execstart:
```
ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000 --storage /etc/Ombi
```

ombi default execstart:
```
ExecStart=/opt/Ombi/Ombi --storage /etc/Ombi/
```

The modifications made by swizzin are only to prevent external access to the port itself and to add the baseurl which is required for proxy function.

@EdTheLoon is there any chance your systemd service has been altered at all or you have tried changing the database backend? It looks like you're running into a permissions issue for the most part. Ombi.db should exist but it does not and I cannot determine why from the info you've given me.

Have you attempted a re-install of the application?

**Comment by EdTheLoon** [comment]
`ombi.service` is shown below and matches the swizzin execstart:

```
adrian@ns3343894 system: cat ombi.service 
[Unit]
Description=Ombi - PMS Requests System
After=network-online.target

[Service]
User=ombi
Group=nogroup
WorkingDirectory=/opt/Ombi/
ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000 --storage /etc/Ombi
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

I will attempt a re-install and paste the terminal outputs in another comment.

**Comment by EdTheLoon** [comment]
Carried out `sudo box update` before removing ombi and re-installing.

```
user@somehost system: sudo box remove ombi
Removing ombi 
Removed /etc/systemd/system/multi-user.target.wants/ombi.service.
user@somehost system: sudo box install ombi
Installing ombi 
Ombi Installation Complete!
```

**Comment by EdTheLoon** [comment]
`sudo journalctl -xe`:

```
user@somehost system: sudo journalctl -xe
-- 
-- Unit ombi.service has finished starting up.
-- 
-- The start-up result is RESULT.
Feb 27 12:29:56 somehost Ombi[11048]: Hello, welcome to Ombi
Feb 27 12:29:56 somehost Ombi[11048]: Valid options are:
Feb 27 12:29:56 somehost Ombi[11048]: Ombi 3.0.4892-master
Feb 27 12:29:56 somehost Ombi[11048]: Copyright (C) 2020 Ombi
Feb 27 12:29:56 somehost Ombi[11048]:   --host       (Default: http://*:5000) Set t
Feb 27 12:29:56 somehost Ombi[11048]:                of URL prefixes to which the s
Feb 27 12:29:56 somehost Ombi[11048]:                http://localhost:123. Use "*" 
Feb 27 12:29:56 somehost Ombi[11048]:                listen for requests on any IP 
Feb 27 12:29:56 somehost Ombi[11048]:                specified port and protocol (f
Feb 27 12:29:56 somehost Ombi[11048]:                protocol (http:// or https://)
Feb 27 12:29:56 somehost Ombi[11048]:                Supported formats vary between
Feb 27 12:29:56 somehost Ombi[11048]:   --storage    Storage path, where we save th
Feb 27 12:29:56 somehost Ombi[11048]:   --baseurl    The base URL for reverse proxy
Feb 27 12:29:56 somehost Ombi[11048]:   --demo       Demo mode, you will never need
Feb 27 12:29:56 somehost Ombi[11048]:                company...
Feb 27 12:29:56 somehost Ombi[11048]:   --help       Display this help screen.
Feb 27 12:29:56 somehost Ombi[11048]:   --version    Display version information.
Feb 27 12:29:58 somehost Ombi[11048]: Unhandled Exception: Microsoft.Data.Sqlite.Sq
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.Data.Sqlite.SqliteException.T
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.Data.Sqlite.SqliteCommand.Pre
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.Data.Sqlite.SqliteCommand.Exe
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Storage.I
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Storage.I
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Query.Int
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Query.Int
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Query.Int
Feb 27 12:29:58 somehost Ombi[11048]:    at Microsoft.EntityFrameworkCore.Query.Int
Feb 27 12:29:58 somehost Ombi[11048]:    at System.Collections.Generic.List`1.AddEn
Feb 27 12:29:58 somehost Ombi[11048]:    at System.Linq.Enumerable.ToList[TSource](
Feb 27 12:29:58 somehost Ombi[11048]:    at Ombi.Program.Main(String[] args) in C:\
Feb 27 12:29:58 somehost systemd[1]: ombi.service: Main process exited, code=dumped
Feb 27 12:29:58 somehost systemd[1]: ombi.service: Failed with result 'core-dump'.
Feb 27 12:29:59 somehost sudo[11088]:   user : TTY=pts/5 ; PWD=/etc/systemd/syste
Feb 27 12:29:59 somehost sudo[11088]: pam_unix(sudo:session): session opened for us
lines 1449-1486/1486 (END)
```

**Comment by EdTheLoon** [comment]
```
cat ombi.service 
[Unit]
Description=Ombi - PMS Requests System
After=network-online.target

[Service]
User=ombi
Group=nogroup
WorkingDirectory=/opt/Ombi/
ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000 --storage /etc/Ombi
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by aburkh** [comment]
I encountered the same issue as @EdTheLoon on Debian 10. The simple fix for me was to remove the original database.
`sudo mv /etc/Ombi/OmbiSettings.db OmbiSettings.db.bak && sudo systemctl start ombi`

Everything is working correctly after that.

**Comment by EdTheLoon** [comment]
Can confirm that the method posted by `aburkh` solved this issue.

> I encountered the same issue as @EdTheLoon on Debian 10. The simple fix for me was to remove the original database.
> `sudo mv /etc/Ombi/OmbiSettings.db OmbiSettings.db.bak && sudo systemctl start ombi`
> 
> Everything is working correctly after that.
